### ISSUE TITLE
Don't strtolower the request

### ISSUE THREAD

**Issue by 9livesdevelopment** [joshhornby/Http#3]
Hi,

Don't strtolower any request. For example when you want to verify a Facebook access token, the token should be sent "as is"

**Comment by joshhornby** [comment]
Fair point.

https://github.com/joshhornby/Http/commit/08138f3a0a14fa8d38a0517d4385cc498ed0939f See the following commit.

**Comment by 9livesdevelopment** [comment]
Cheers!
