### ISSUE TITLE
cannot work on laravel 5

### ISSUE THREAD

**Issue by blackmamb41** [joshhornby/Http#5]
It's cannot install using laravel 5?
![image](https://cloud.githubusercontent.com/assets/11955657/19149325/7f2facae-8beb-11e6-8e1e-62663276a57b.png)

**Comment by joshhornby** [comment]
This package is no longer supported I'm afraid @blackmamb41.

Guzzle is pretty simple to set up these days - http://docs.guzzlephp.org/en/latest/
